# Generated by Django 6.0.5 on 2026-05-22 12:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_initial'),
        ('payments', '0004_commission_fields'),
        ('technicians', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('commission_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_done', models.CharField(help_text='Service category from the booking (e.g. Plumbing).', max_length=100)),
                ('full_amount', models.DecimalField(decimal_places=2, help_text='Total amount paid by the customer.', max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, help_text='20% platform fee retained by eFundi.', max_digits=10)),
                ('technician_earnings', models.DecimalField(decimal_places=2, help_text='80% credited to the technician wallet.', max_digits=10)),
                ('payment_method', models.CharField(max_length=20)),
                ('paid_at', models.DateTimeField(help_text='Timestamp of the confirmed M-Pesa transaction.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='customers.client')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission_record', to='payments.payment')),
                ('technician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='technicians.technician')),
            ],
            options={
                'verbose_name': 'Commission',
                'verbose_name_plural': 'Commissions',
                'db_table': 'commissions',
                'ordering': ['-paid_at'],
                'indexes': [models.Index(fields=['paid_at'], name='commission_paid_at_idx'), models.Index(fields=['payment_method'], name='commission_method_idx')],
            },
        ),
    ]
