# Generated by Django 6.0.5 on 2026-05-21 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
        ('technicians', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='technician_id',
            field=models.ForeignKey(blank=True, db_column='technician_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to='technicians.technician'),
        ),
        migrations.AddField(
            model_name='bookingbroadcast',
            name='booking_id',
            field=models.ForeignKey(db_column='booking_id', on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='bookingbroadcast',
            name='technician_id',
            field=models.ForeignKey(db_column='technician_id', on_delete=django.db.models.deletion.CASCADE, related_name='received_broadcasts', to='technicians.technician'),
        ),
        migrations.AddField(
            model_name='technicianlocation',
            name='technician_id',
            field=models.OneToOneField(db_column='technician_id', on_delete=django.db.models.deletion.CASCADE, related_name='live_location', to='technicians.technician'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='booking_status_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['service_category'], name='booking_category_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['scheduled_time'], name='booking_scheduled_time_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['created_at'], name='booking_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['assignment_expires_at'], name='booking_expires_at_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingbroadcast',
            index=models.Index(fields=['status'], name='broadcast_status_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingbroadcast',
            index=models.Index(fields=['booking_id', 'status'], name='broadcast_booking_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookingbroadcast',
            unique_together={('booking_id', 'technician_id')},
        ),
    ]
