# Generated by Django 6.0.5 on 2026-06-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_service_price_list_and_booking_pricing'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='servicepricelist',
            name='unique_category_fault',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='description',
        ),
        migrations.AlterField(
            model_name='booking',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Company bill — total amount the customer pays.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='booking',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='servicepricelist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='technicianlocation',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='technicianlocation',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterUniqueTogether(
            name='servicepricelist',
            unique_together={('category', 'fault_name')},
        ),
    ]
