# Generated by Codex on 2026-06-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_restore_booking_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
        migrations.AlterField(
            model_name='booking',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
        migrations.AlterField(
            model_name='technicianlocation',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
        migrations.AlterField(
            model_name='technicianlocation',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
    ]
