# Generated by Django 6.0.5 on 2026-05-21 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('event_type', models.CharField(choices=[('New Booking', 'New Booking'), ('Booking Broadcasted', 'Booking Broadcasted'), ('Booking Accepted', 'Booking Accepted'), ('Booking Declined', 'Booking Declined'), ('Booking Rejected', 'Booking Rejected'), ('Booking Completed', 'Booking Completed'), ('Booking Cancelled', 'Booking Cancelled'), ('Payment Successful', 'Payment Successful'), ('Withdrawal Requested', 'Withdrawal Requested'), ('Withdrawal Approved', 'Withdrawal Approved'), ('Withdrawal Rejected', 'Withdrawal Rejected'), ('System', 'System')], default='System', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type'], name='notification_event_idx'), models.Index(fields=['is_read'], name='notification_is_read_idx'), models.Index(fields=['created_at'], name='notification_created_at_idx')],
            },
        ),
    ]
