"""
Django settings for efundi_app project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
import ssl
import certifi
from decimal import Decimal
from pathlib import Path
from datetime import timedelta
import environ
from django.urls import reverse_lazy

# macOS Homebrew Python doesn't pick up system CA certs via ssl.create_default_context().
# Monkey-patch it to always use certifi's bundle so SMTP STARTTLS (and all SSL) works.
os.environ['REQUESTS_CA_BUNDLE'] = certifi.where()
_orig_create_default_context = ssl.create_default_context
def _certifi_create_default_context(purpose=ssl.Purpose.SERVER_AUTH, **kwargs):
    kwargs.setdefault('cafile', certifi.where())
    return _orig_create_default_context(purpose, **kwargs)
ssl.create_default_context = _certifi_create_default_context

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize the environment variable
env = environ.Env(
    DEBUG=(bool, False)
)

# Read the env file if it exists
env.read_env(str(BASE_DIR / '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-7r)xg3@v4^6ih2ka@4p1sm-i_f=#6bl1ssfok27tkm6xsofef1')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=True)

_NGROK_URL = env('NGROK_URL', default='').rstrip('/')
# Render sets this automatically to the service's public URL — lets the
# backend self-detect its own host for ALLOWED_HOSTS/CORS/CSRF without any
# manual env var configuration after deploy.
_RENDER_URL = env('RENDER_EXTERNAL_URL', default='').rstrip('/')
_PUBLIC_URL = _NGROK_URL or _RENDER_URL
_PUBLIC_HOST = _PUBLIC_URL.replace('https://', '').replace('http://', '')

ALLOWED_HOSTS = ['localhost', '127.0.0.1']
if _PUBLIC_HOST:
    ALLOWED_HOSTS.append(_PUBLIC_HOST)

# Base URL used to build absolute links in emails when there is no HTTP request
# context (e.g. signals, Celery tasks, admin-triggered emails).
# Override in .env for staging/production.
SITE_URL = _PUBLIC_URL or env('SITE_URL', default='http://localhost:8000')

# Frontend origin — used for links in emails that must open the React app
# (e.g. /verify-email, /reset-password). Override in .env for production.
FRONTEND_URL = env('FRONTEND_URL', default='http://localhost:5173')


# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

    'rest_framework',
    'corsheaders',
    'drf_spectacular',

    'accounts.app.AccountsConfig',
    'bookings.app.BookingsConfig',
    'common.app.CommonConfig',
    'customers.app.CustomersConfig',
    'notifications.app.NotificationsConfig',
    'payments.app.PaymentsConfig',
    'mpesa.apps.MpesaConfig',
    'reviews.app.ReviewsConfig',
    'technicians.app.TechniciansConfig',
    'commissions.app.CommissionsConfig',
]

AUTH_USER_MODEL = 'accounts.User'
SITE_ID = 1

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)


SOCIALACCOUNT_ADAPTER = 'accounts.adapters.AdminGoogleSocialAccountAdapter'

# Google OAuth — Client ID used to verify ID tokens from the React frontend
GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID', '')

UNFOLD = {
    "SITE_TITLE": "eFundi Admin",
    "SITE_HEADER": "eFundi",
    "SITE_BRAND": "eFundi",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "SIDEBAR": {
        "show_search": True,
        "navigation": [
            {
                "title": "Navigation",
                "collapsible": False,
                "items": [
                    {
                        "title": "Dashboard",
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                ],
            },
            {
                "title": "Customers",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Clients",
                        "icon": "person",
                        "link": reverse_lazy("admin:customers_client_changelist"),
                    },
                    {
                        "title": "Transactions",
                        "icon": "receipt_long",
                        "link": reverse_lazy("admin:customers_customertransaction_changelist"),
                    },
                ],
            },
            {
                "title": "Technicians",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "All Technicians",
                        "icon": "engineering",
                        "link": reverse_lazy("admin:technicians_technician_changelist"),
                    },
                    {
                        "title": "Transactions",
                        "icon": "receipt_long",
                        "link": reverse_lazy("admin:technicians_techniciantransaction_changelist"),
                    },
                ],
            },
            {
                "title": "Bookings",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Bookings",
                        "icon": "event",
                        "link": reverse_lazy("admin:bookings_booking_changelist"),
                    },
                    {
                        "title": "Broadcasts",
                        "icon": "broadcast_on_home",
                        "link": reverse_lazy("admin:bookings_bookingbroadcast_changelist"),
                    },
                    {
                        "title": "Technician Locations",
                        "icon": "location_on",
                        "link": reverse_lazy("admin:bookings_technicianlocation_changelist"),
                    },
                ],
            },
            {
                "title": "Payments",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Commissions",
                        "icon": "percent",
                        "link": reverse_lazy("admin:commissions_commission_changelist"),
                    },
                    {
                        "title": "Payments",
                        "icon": "payments",
                        "link": reverse_lazy("admin:payments_payment_changelist"),
                    },
                    {
                        "title": "Wallets",
                        "icon": "account_balance_wallet",
                        "link": reverse_lazy("admin:payments_technicianwallet_changelist"),
                    },
                    {
                        "title": "Withdrawals",
                        "icon": "money_off",
                        "link": reverse_lazy("admin:payments_withdrawalrequest_changelist"),
                    },
                ],
            },
            {
                "title": "Notifications",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Notifications",
                        "icon": "notifications",
                        "link": reverse_lazy("admin:notifications_notification_changelist"),
                    },
                ],
            },
            {
                "title": "Reviews",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Reviews",
                        "icon": "star",
                        "link": reverse_lazy("admin:reviews_review_changelist"),
                    },
                ],
            },
            {
                "title": "User Management",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "All Users",
                        "icon": "manage_accounts",
                        "link": reverse_lazy("admin:accounts_user_changelist"),
                    },
                    {
                        "title": "Technicians",
                        "icon": "engineering",
                        "link": reverse_lazy("admin:accounts_accounttechnician_changelist"),
                    },
                    {
                        "title": "Clients",
                        "icon": "person",
                        "link": reverse_lazy("admin:accounts_accountclient_changelist"),
                    },
                ],
            },
        ],
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'efundi_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates', BASE_DIR / 'utils' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'efundi_app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Media files (user uploads — technician certificates, profile pics, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default Primary Key Fields
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS SETTINGS
CORS_ALLOWED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    FRONTEND_URL,
]
if _PUBLIC_URL:
    CORS_ALLOWED_ORIGINS.append(_PUBLIC_URL)

CORS_ALLOW_CREDENTIALS = True

# CSRF trusted origins — required for Django 4+ when receiving HTTPS requests
# (ALLOWED_HOSTS alone is not enough for cross-origin POST/PATCH/DELETE)
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    FRONTEND_URL,
]
if _PUBLIC_URL:
    CSRF_TRUSTED_ORIGINS.append(_PUBLIC_URL)

# BUSINESS RULES
COMMISSION_RATE = Decimal('0.20')           # 20% platform fee retained from each payment
MINIMUM_WITHDRAWAL = Decimal('5')          # Minimum manual withdrawal amount in KSh
AUTO_WITHDRAWAL_THRESHOLD = Decimal('200') # Auto-payout triggered when wallet balance >= this

# INTASEND PAYMENT GATEWAY
# Dashboard: https://sandbox.intasend.com  (test)  |  https://app.intasend.com  (live)
# Webhook URLs to register in Intasend dashboard → Settings → Webhooks:
#   STK Push result  : <SITE_URL>/api/v1/payments/intasend/callback/
#   Send Money result: <SITE_URL>/api/v1/payments/intasend/payout/callback/
INTASEND_PUBLISHABLE_KEY = env('INTASEND_PUBLISHABLE_KEY', default='')
INTASEND_API_KEY = env('INTASEND_API_KEY', default='')
INTASEND_TEST_MODE = env.bool('INTASEND_TEST_MODE', default=False)

# SWAGGER SETTINGS
SWAGGER_SETTINGS = {
    'DEFAULT_INFO': 'efundi_app.urls.api_info',
    'USE_SESSION_AUTH': False,
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            'description': 'JWT Authorization header using the Bearer scheme. Example: "Authorization: Bearer {token}"'
        }
    },
    'TAGS_SORTER': 'alpha',
    'OPERATIONS_SORTER': 'alpha',
}

# REST FRAMEWORK SETTINGS
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,
    'USER_ID_FIELD': 'user_id',
    'USER_ID_CLAIM': 'user_id',
}

# Redis cache settings for Celery and general caching
REDIS_URL = env('REDIS_URL', default='redis://127.0.0.1:6379/1')

# Allows running without a Redis instance (e.g. quick demo deploys) by
# falling back to Django's in-process cache. Defaults to Redis as before.
if env.bool('USE_REDIS_CACHE', default=True):
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        }
    }

# Email settings
# Use SMTP when EMAIL_HOST_USER is provided in .env, otherwise fall back to
# the console backend (prints emails to the terminal — useful when no SMTP
# credentials are available).
EMAIL_HOST = env('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='eFundi <noreply@efundi.com>')

if EMAIL_HOST_USER:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
else:
    # No SMTP credentials — print emails to the terminal instead.
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Render's free tier blocks outbound SMTP ports (25/465/587), so a real SMTP
# attempt hangs until the worker times out and gets killed. Default to the
# console backend there, regardless of EMAIL_HOST_USER.
if _RENDER_URL and not _NGROK_URL:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Still allow an explicit override via env for any other deployment target.
EMAIL_BACKEND = env('EMAIL_BACKEND', default=EMAIL_BACKEND)

# Celery settings
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
# When True, .delay()/.apply_async() run tasks synchronously in-process —
# no broker or separate worker needed. Useful for quick demo deploys.
CELERY_TASK_ALWAYS_EAGER = env.bool('CELERY_TASK_ALWAYS_EAGER', default=False)
CELERY_TASK_EAGER_PROPAGATES = CELERY_TASK_ALWAYS_EAGER
# Use 'solo' pool on Windows (prefork uses Unix semaphores which Windows denies).
# On Linux/Mac in production, remove this line to use the default prefork pool.
if sys.platform == 'win32':
    CELERY_WORKER_POOL = 'solo'

# drf-spectacular settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'eFundi API',
    'DESCRIPTION': (
        '## eFundi Service Marketplace API\n\n'
        '### How to authenticate\n'
        '1. **Credentials (easiest)** — click **Authorize**, choose `credentialsAuth`, '
        'enter your username & password. Swagger will fetch and apply your token automatically.\n'
        '2. **Paste token** — call `POST /api/v1/auth/token/` manually, copy the `access` '
        'value, then click **Authorize** and paste it into `jwtAuth`.\n\n'
        '### Contacts\n'
        '- For API issues, contact the backend team: ** oloobrian89@gmail.com **\n\n'
        '### Role-based endpoints\n'
        'Use the **🔍 Filter** box (top of this page) to show only the APIs that apply to you:\n\n'
        '| Type your role | What you will see |\n'
        '|---|---|\n'
        '| `Authentication` | Registration, login, token refresh — public |\n'
        '| `Customer` | Create services, track status, reviews, make payments |\n'
        '| `Technician` | Accept/decline jobs, live location, wallet, withdrawals |\n'
        '| `Admin` | User management, resolve issues |\n'
        '| `Super Admin` | All endpoints, including admin-only ones |\n\n'
    ),
    'VERSION': '1.0.0',

    # Add the OAuth2 password-flow scheme for the Swagger Authorize dialog
    'APPEND_COMPONENTS': {
        'securitySchemes': {
            'credentialsAuth': {
                'type': 'oauth2',
                'description': (
                    'Log in with your eFundi username and password. '
                    'Swagger will call the token endpoint and set Bearer auth automatically.'
                ),
                'flows': {
                    'password': {
                        'tokenUrl': '/api/v1/accounts/swagger-login/',
                        'scopes': {},
                    },
                },
            },
        },
    },

    # Swagger UI behaviour
    'SWAGGER_UI_SETTINGS': {
        'persistAuthorization': True,
        'displayOperationId': False,
        'displayRequestDuration': True,
        'filter': True,
        'docExpansion': 'none',
        # Pre-fill client_id so users only need to enter username + password.
        # client_secret can be left blank — our endpoint ignores it.
        'initOAuth': {
            'clientId': 'efundi',
            'clientSecret': '',
            'scopes': '',
        },
    },

    # Tag definitions shown at the bottom of Swagger UI
    'TAGS': [
        {
            'name': 'Authentication',
            'description': '🔑 Registration, login, token endpoints — no auth required',
        },
        {
            'name': 'Customer',
            'description': '👤 Endpoints for customers — create bookings, payments, reviews',
        },
        {
            'name': 'Technician',
            'description': '🔧 Endpoints for technicians — accept jobs, location, wallet',
        },
        {
            'name': 'Admin',
            'description': '🛡️ Admin-only management endpoints',
        },
    ],
}

# LOGGING SETTINGS
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'simple': {
        'format': '{levelname} {message}',
        'style': '{',
    },

    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': 'django.log',
            'formatter': 'verbose',
        },
    },

    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },

    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'myapp': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}
