# Generated by Django 6.0.5 on 2026-05-21 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Technician Wallet',
                'verbose_name_plural': 'Technician Wallets',
                'db_table': 'technician_wallets',
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('phone_number', models.CharField(max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Withdrawal Request',
                'verbose_name_plural': 'Withdrawal Requests',
                'db_table': 'withdrawal_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(choices=[('payments', 'Payments'), ('wallets', 'Wallets'), ('withdrawals', 'Withdrawals'), ('technician_transactions', 'Technician Transactions'), ('customer_transactions', 'Customer Transactions')], max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('filters', models.JSONField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='exports/')),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Export Job',
                'verbose_name_plural': 'Export Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('payer_phone_number', models.CharField(blank=True, help_text='Mobile number used for M-Pesa payment.', max_length=10, null=True)),
                ('account_reference', models.CharField(blank=True, help_text='Account reference passed to M-Pesa STK Push.', max_length=100, null=True)),
                ('merchant_request_id', models.CharField(blank=True, help_text='M-Pesa merchant request identifier.', max_length=100, null=True)),
                ('checkout_request_id', models.CharField(blank=True, help_text='M-Pesa checkout request identifier.', max_length=100, null=True)),
                ('conversation_id', models.CharField(blank=True, help_text='M-Pesa conversation identifier from callbacks.', max_length=100, null=True)),
                ('result_code', models.CharField(blank=True, help_text='Result code returned by M-Pesa for the request.', max_length=20, null=True)),
                ('result_description', models.CharField(blank=True, help_text='Result description returned by M-Pesa callback.', max_length=255, null=True)),
                ('callback_metadata', models.JSONField(blank=True, help_text='Raw callback payload from the M-Pesa gateway.', null=True)),
                ('transaction_date', models.DateTimeField(blank=True, help_text='Date and time of the M-Pesa transaction.', null=True)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Successful', 'Successful'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('M-Pesa', 'M-Pesa'), ('Cash', 'Cash'), ('Card', 'Card')], default='M-Pesa', max_length=20)),
                ('is_credited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_id', models.ForeignKey(db_column='booking_id', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
