# Generated by Django 6.0.5 on 2026-05-21 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('technicians', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianwallet',
            name='technician_id',
            field=models.OneToOneField(db_column='technician_id', on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='technicians.technician'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='technician_id',
            field=models.ForeignKey(db_column='technician_id', on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='technicians.technician'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_status'], name='payment_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method'], name='payment_method_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_reference'], name='payment_reference_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['merchant_request_id'], name='mpesa_merchant_request_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['checkout_request_id'], name='mpesa_checkout_request_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['conversation_id'], name='mpesa_conversation_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payer_phone_number'], name='mpesa_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['status'], name='withdrawal_status_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['created_at'], name='withdrawal_created_at_idx'),
        ),
    ]
