# Generated by Django 6.0.5 on 2026-05-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payer_phone_number',
            field=models.CharField(blank=True, help_text='Mobile number used for M-Pesa payment.', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
