# Generated by Django 6.0.5 on 2026-05-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_phone_number_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='commission_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='20% platform commission retained by eFundi.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='technician_earnings',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='80% of payment credited to the technician wallet.', max_digits=10, null=True),
        ),
    ]
