# Generated by Django 6.0.5 on 2026-05-21 15:25

import django.contrib.auth.models
import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the user.', primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(help_text="User's email address, used for authentication\n                     and communication.", max_length=254, unique=True, verbose_name='Email Address')),
                ('verified_email', models.BooleanField(default=False, help_text="Designates whether the user's email has been verified.")),
                ('verified_phone_number', models.BooleanField(default=False, help_text="Designates whether the user's phone number has been verified.")),
                ('phone_number', models.CharField(help_text="User's phone number, used for contact.", max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone number must contain exactly 10 digits.', regex='^\\d{10}$')], verbose_name='Phone Number')),
                ('first_name', models.CharField(help_text="User's first name.", max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(help_text="User's last name.", max_length=30, verbose_name='Last Name')),
                ('username', models.CharField(help_text='Unique username for the user, used for authentication.', max_length=150, unique=True)),
                ('profile_picture', models.ImageField(blank=True, help_text='Profile picture of the user.', null=True, upload_to='profile_pictures/')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.\n                    Unselect this instead of deleting accounts.', verbose_name='is_active')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into the admin site.')),
                ('is_verified', models.BooleanField(default=False, help_text='Designates whether the user has completed the verification process.')),
                ('last_login', models.DateTimeField(blank=True, help_text='The last time the user logged in.', null=True)),
                ('role', models.CharField(choices=[('Super Admin', 'Super Admin'), ('Admin', 'Admin'), ('Customer', 'Customer'), ('Technician', 'Technician')], default='Customer', help_text='The role of the user, which determines their permissions\n                    and access level in the application.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the user account was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the user account was last updated.')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'efundi_user',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
