# Generated by Django 6.0.5 on 2026-05-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as active.\n                    Unselect this instead of deleting accounts.', verbose_name='is_active'),
        ),
    ]
