# Generated by Django 6.0.5 on 2026-05-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Latitude of the user's default location.", max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='default_location',
            field=models.CharField(blank=True, help_text="User's preferred default service address.", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='default_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Longitude of the user's default location.", max_digits=9, null=True),
        ),
    ]
