# Generated by Django 6.0.5 on 2026-06-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_default_latitude_user_default_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text="Latitude of the user's default location.", max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='default_longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text="Longitude of the user's default location.", max_digits=11, null=True),
        ),
    ]
