# Generated by Django 6.0.5 on 2026-06-03 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_increase_coordinate_precision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='default_latitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='default_location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='default_longitude',
        ),
    ]
