# Generated by Django 6.0.5 on 2026-05-21 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianTransaction',
            fields=[
            ],
            options={
                'verbose_name': 'Technician Transaction',
                'verbose_name_plural': 'Technician Transactions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payments.payment',),
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='accounts.User.first_name')),
                ('last_name', models.CharField(max_length=30, verbose_name='accounts.User.last_name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='accounts.User.email')),
                ('phone_number', models.CharField(max_length=10, unique=True, verbose_name='accounts.User.phone_number')),
                ('role', models.CharField(default='Technician', max_length=20, verbose_name='accounts.User.role')),
                ('specialization', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True, null=True)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False, verbose_name='accounts.User.is_active')),
                ('verification_status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('credentials', models.FileField(blank=True, null=True, upload_to='technician_credentials/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.OneToOneField(db_column='user_id', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='technician_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Technician',
                'verbose_name_plural': 'Technicians',
                'db_table': 'efundi_technician',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='technician_email_idx'), models.Index(fields=['phone_number'], name='technician_phone_number_idx')],
                'constraints': [models.UniqueConstraint(fields=('email',), name='unique_technician_email'), models.UniqueConstraint(fields=('phone_number',), name='unique_technician_phone_number')],
            },
        ),
    ]
