# Generated by Django 6.0.5 on 2026-05-27 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicians', '0002_technician_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Electrical', 'Electrical'), ('Plumbing', 'Plumbing'), ('Carpentry', 'Carpentry'), ('Cleaning', 'Cleaning'), ('Other', 'Other')], max_length=50)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('verification_status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='technician_certificates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='technicians.technician')),
            ],
            options={
                'db_table': 'technician_specializations',
                'ordering': ['name'],
                'unique_together': {('technician', 'name')},
            },
        ),
    ]
