# Generated by Django 6.0.5 on 2026-05-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicians', '0003_technicianspecialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='specialization',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
