# Generated by Django 6.0.5 on 2026-05-28 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technicians', '0004_specialization_blank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='specialization',
        ),
    ]
