# Generated by Django 6.0.5 on 2026-05-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicians', '0005_remove_specialization_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='years_of_experience',
        ),
        migrations.AddField(
            model_name='technicianspecialization',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
