# Generated by Django 6.0.5 on 2026-05-28 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technicians', '0006_move_years_of_experience_to_specialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='credentials',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='skills',
        ),
    ]
