# Generated by Django 6.0.5 on 2026-06-03 13:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicians', '0010_add_technician_specialization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technicianspecialization',
            options={'ordering': ['name'], 'verbose_name': 'Technician Specialization', 'verbose_name_plural': 'Technician Specializations'},
        ),
        migrations.RemoveField(
            model_name='technician',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='years_of_experience',
        ),
        migrations.AlterField(
            model_name='technicianspecialization',
            name='technician',
            field=models.ForeignKey(db_column='technician_id', on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='technicians.technician'),
        ),
        migrations.AlterField(
            model_name='technicianspecialization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2026, 6, 3, 13, 5, 55, 453398, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
