# Generated by Codex on 2026-06-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicians', '0011_alter_technicianspecialization_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicianspecialization',
            name='name',
            field=models.CharField(choices=[
                ('Electrical', 'Electrical'),
                ('Plumbing', 'Plumbing'),
                ('Carpentry', 'Carpentry'),
                ('Cleaning', 'Cleaning'),
                ('Other', 'Other'),
                ('Fridge Repair', 'Fridge Repair'),
                ('Washing Machine', 'Washing Machine'),
                ('Cooker & Oven', 'Cooker & Oven'),
                ('Television', 'Television'),
                ('Security Systems', 'Security Systems'),
                ('Solar & Power', 'Solar & Power'),
                ('Small Appliances', 'Small Appliances'),
                ('Other Technical', 'Other Technical'),
            ], max_length=50),
        ),
    ]
