# Generated by Django 6.0.5 on 2026-05-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='accounts.User.first_name')),
                ('last_name', models.CharField(max_length=30, verbose_name='accounts.User.last_name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='accounts.User.email')),
                ('phone_number', models.CharField(max_length=10, unique=True, verbose_name='accounts.User.phone_number')),
                ('role', models.CharField(default='Customer', max_length=20, verbose_name='accounts.User.role')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'efundi_client',
                'ordering': ['-created_at'],
            },
        ),
    ]
