# Generated by Django 6.0.5 on 2026-05-21 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTransaction',
            fields=[
            ],
            options={
                'verbose_name': 'Customer Transaction',
                'verbose_name_plural': 'Customer Transactions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payments.payment',),
        ),
        migrations.AddField(
            model_name='client',
            name='user_id',
            field=models.OneToOneField(db_column='user_id', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['email'], name='client_email_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['phone_number'], name='client_phone_number_idx'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_client_email'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('phone_number',), name='unique_client_phone_number'),
        ),
    ]
